

# DISPLAY
(SCREEN_WIDTH, SCREEN_HEIGHT) = (1280, 720)
GAME_TITLE = "Cash Cow I: The Cashening"
DISPLAY_FILEPATH_BACKDROP = "Assets/Map/field.png"
FRAME_RATE = 60


# COW
COW_FILEPATH_NORMAL = "Assets/Cow/normal-cow.png"
COW_SIZE = (128, 128)
COW_FILEPATH_SPRAY = "Assets/Cow/spray.png"
COW_SPRAY_SIZE = (128, 128)
COW_SPRAY_OFFSET_X = 110
COW_SPRAY_OFFSET_Y = 20
COW_SPEED_UP = 5
COW_SPEED_DOWN = 5
COW_SPEED_RIGHT = 6
COW_SPEED_LEFT = 6


# ENEMY
ENEMY_FILEPATH_NORMAL = "Assets/Enemy/money-with-wings.png"
ENEMY_FILEPATH_LOOT = "Assets/Enemy/money-bag.png"
ENEMY_SIZE = (75, 75)
ENEMY_SPAWN_TIME = 1000


# GAME LOGIC
LOGIC_MILKMETER_MAX = 200
LOGIC_SCOREBOARD_INIT = 0
